name: Zandero Vert.X build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ubuntu-latest
      ports:
        - 4444:4444

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean compile test
